theme: jekyll-theme-primer # Sostituisci con il nome del tema che hai scelto
title: MF Shopify Theme Docs
description: Official guides, section configurations, and settings for the Shopify Themes developed by Marco Francaviglia.
